### ISSUE TITLE
Ferramenta muito util

### ISSUE THREAD

**Issue by Kyo-70** [klyte45/EmpireOfSinFiles#2]
Eaw, tava dando uma pesquisa na net e me deparei com um programa muito util. um que ele compara dois arquivos de texto onde mostra oque está faltando naquela linha em questão. não sei se você já conhece é esse aqui:

https://winmerge.org/

**Comment by klyte45** [comment]
Agradeço pela dica! Na verdade eu uso planilhas do excel para verificar o que mudou de uma versão pra outra, e pra colocar lado a lado a versão em inglês com a minha tradução nova quando necessário...
