### ISSUE TITLE
Duvida sobre a tradução

### ISSUE THREAD

**Issue by Kyo-70** [klyte45/EmpireOfSinFiles#4]
Opa, eaw tranquilo, espero que sim, sei que talvez possa ser chato, mas queria te perguntar pretende atualizar a tradução? ou desanimou kkk acontece.

**Comment by klyte45** [comment]
Pretender pretendo, o detalhe é que agora estou com foco no Skylines. Tenho que achar um tempo pra rodar a versão nova do jogo pra atualizar...

**Comment by Kyo-70** [comment]
> Pretender pretendo, o detalhe é que agora estou com foco no Skylines. Tenho que achar um tempo pra rodar a versão nova do jogo pra atualizar...

Tendi que bom.. eu fui dar uma olhada e mudou muita coisa.. pretendia mexer ve se conseguia traduzir.. mas é bem foda.. tu sabe fazer a divisão no excell tipo deixar as linhas de comando em uma tabela e a descrição em outra.. tava tentando e não consegui
